### ISSUE TITLE
Docker Global Hack Day

### ISSUE THREAD

**Issue by daviddias** [dockerlisbon/community#10]
Hi all! 

Docker, Inc has pinged to know if we are interested in participating in the [Global Docker Hack Day](https://blog.docker.com/2014/10/announcing-docker-global-hack-day-2/).

The goal is to hack on the new features of Docker 1.3 considering the set of judging criteria. See this [blog post](https://blog.docker.com/2014/10/announcing-docker-global-hack-day-2/) for more info. 

Since we are in a different timezone (8 hours ahead), we can organize ourselves in two different formats
## Format options

1) Oct 30th from 6:30pm - 1am (live streaming) + hacking all night
2) Oct 31st - Start in the morning and watch the video recording instead of live streaming + hack all day long

Sounds like fun? Please comment your interest, if we get at least 12 people to participate, I think we can have a pretty fun event! :)

**Comment by joantune** [comment]
I missed this comment untill now. I can guive a 5m talk (max) about how i'm
using docker, but it's not enough to fill up more than 2 slides (max) and
it is nothing new, but it's my experience and what I like about it and how
I used it in the projects since I learned about it through you guys

On Tue, Dec 16, 2014 at 6:29 PM, David Dias <notifications@github.com>
wrote:

> @joantune <https://github.com/joantune> would you be interested to talk
> about your Docker Story?
> http://www.meetup.com/DockerLisbon/events/219278512/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dockerlisbon/group/issues/10#issuecomment-67207243>.
>



-- 
João Antunes
http://web.ist.utl.pt/~joao.a.p.antunes/
<http://web.ist.utl.pt/~joao.a.p.antunes/?reference=emailSig>
